# manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argo-test2 # Указываем неймспейс, в котором будет работать наше приложение
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23 # Используем конкретную версию образа
        ports:
        - containerPort: 80
